### ISSUE TITLE
Create Backend Unit Tests

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/aww-rats-battle-functions#18]
@GV14982 can you fill in deets on this issue?

**Comment by GV14982** [comment]
For this we need to add unit tests for all of our serverless functions that get used by Hasura.

For the test running I'll setup[jest](https://jestjs.io/), we can use [supertest](https://github.com/visionmedia/supertest) for handling the HTTP, and setup [mocks](https://jestjs.io/docs/mock-functions) for our graphql service.
