### ISSUE TITLE
✨ Finish API logic

### ISSUE THREAD

**Issue by GV14982** [ClickPop/aww-rats-battle-functions#5]
We still have a couple of things that the API needs.

- [x] Add actions for handling the various encounters
  - [x] Solo encounters
    - This is already stubbed out in the [functions repo](https://github.com/ClickPop/aww-rats-battle-functions/blob/main/src/functions/encounters/index.ts). We just need to switch it from using the Prisma client to using the Hasura endpoint
  - [ ] Raid contributions
  - [ ] Gauntlet attempts

The docs for writing custom actions are available [here](https://hasura.io/docs/latest/graphql/core/actions/index.html). Feel free to take a look at my [login action handler](https://github.com/ClickPop/aww-rats-battle-functions/blob/4652111b4f8a4766a8be79e11e2a904d980dc3cf/src/functions/auth/index.ts#L5)

**Comment by TahmidChowdhury** [comment]
https://github.com/ClickPop/aww-rats-battle-functions/pull/7
Added a new branch `api-encounters`

**Comment by GV14982** [comment]
Let's call this good for now.
